# Teoria do POO

"""
PROCEDIMENTO: SÃO RESPOSTAS (MENSAGENS) QUE UM DETERMINADO METODO REALIZA.

FUNÇÕES: SÃO TRANSAÇÕES DE DADOS QUE UMA FUNÇAO REALIZA, OU SEJA, ME RETORNA
         DADOS AO INVES DE MENSAGENS. EXECUTA UMA DETERMINADA AÇÕES. LEMBRAR
         DO EXEMPLO DO PROFESSOR DE APAGAR E ACENDER AS LUZES COM A ALEXA.

ENCAPSULAMENTO: PROTEGER UM ATRIBUTOS OU VARIAVEIS.


"""